# Generated by Django 3.0.2 on 2020-02-05 12:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disc', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('cat_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, help_text='(optional)', upload_to='article/videos')),
                ('thumbnail', models.ImageField(blank=True, help_text='(optional)', upload_to='article/thumbnails')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(default='1--', on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
    ]
