# Generated by Django 3.0.2 on 2020-05-14 16:42

from django.db import migrations
import easy_thumbnails.fields
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='def.jpg', upload_to=news.models.article_path),
        ),
    ]
