# Generated by Django 3.0.2 on 2020-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200223_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='def.jpg', help_text='(optional)', upload_to='article/thumbnails'),
        ),
    ]
