# Generated by Django 3.0.2 on 2020-04-07 13:49

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='def.jpg', help_text='(optional)', upload_to=news.models.article_path),
        ),
    ]
