# Generated by Django 3.0.2 on 2020-03-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200223_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(default='1--', to='news.Category'),
        ),
    ]
