# Generated by Django 3.0.2 on 2020-04-17 13:04

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200407_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='(optional)', upload_to=news.models.article_path),
        ),
    ]
