# Generated by Django 3.0.2 on 2020-04-17 14:58

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200417_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='def.jpg', upload_to=news.models.article_path),
        ),
    ]
