# Generated by Django 3.0.2 on 2020-04-18 23:05

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200418_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='youtube video optional', null=True),
        ),
    ]
