# Generated by Django 3.0.2 on 2020-04-19 00:19

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200418_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
