# Generated by Django 3.0.2 on 2020-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200419_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='news.Categoryies'),
        ),
    ]
