# Generated by Django 3.0.2 on 2020-04-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200422_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categoryies',
        ),
    ]
